config/routes.rb
ArcticIndexClone::Application.routes.draw do

  resources :feedbacks

  match "jobs/job_select" =>'jobs#job_select', :method => :get, :as => :job_select
  resources :jobs, :except => [:destroy]
  
  resources :admin, :only => [:index, :destroy]
  resources :events

  match "search" =>'search#index', :method => :get

  resources :companies, :except => [:destroy]
  resources :people do
    resources :companies, :controller => :people_companies
  end

  resources :users#, :only => [:new, :create, :show, :edit]
  match 'profile'   => 'users#profile',  :as => :profile
  match 'profile/edit'   => 'users#edit',  :as => :profile
  
  resource  :session, :only => [:new, :create, :destroy]
  resources :investors, :only => :index
  resources :abuses, :only => [:create, :desatroy]
  resources :authorizations, :only => :destroy

  match 'signup'   => 'users#new',        :as => :signup
  match 'register' => 'users#create',     :as => :register
  match 'login'    => 'sessions#new',     :as => :login
  match 'logout'   => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match '/auth/:provider/callback', :to => 'authorizations#create'

  root :to => "home#index"
end

app/models/person.rb
require 'paperclip'

class Person < ActiveRecord::Base
  validates :name, :presence => true
  belongs_to :country
  has_many :job_persons
  has_many :person_companies
  has_many :companies, :through => :person_companies
  
  has_attached_file :picture, :styles => { :big => "225x215>", :thumb => "70x35>" },
    :url=>'/images/people/:id/:style/:filename',
    :default_url=>'/images/no_image_:style.png'
  validates_attachment_size :picture, :less_than => 1.megabyte
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/gif']


  #returns comma-formated full name
  def full_name
    self.name ? "#{self.name.split(' ')[0..-2].join(' ')}, #{self.name.split(' ')[-1]}" : ''
  end
  
  def person_name
    self.name ? "#{self.name.split(' ')[0..-2].join(' ')} #{self.name.split(' ')[-1]}" : ''
  end

  def person_name=(nm)
    if nm != ''
      if self.new_record?
        self.name = "#{nm.split(' ')[1..-1].join(' ')} #{nm.split(' ')[0]}"
      else
        part_1 = nm.split(' ')[1..-1].join(' ')
        part_2 = nm.split(' ')[0]
        self.name = "#{part_2} #{part_1}"
      end
    else
      self.name = ''
    end
  end

  scope :investors, where(:investor => true)

  def current_companies
    person_companies.select{|x| x if x.active}.collect{|x| x.company}
  end

  def incurrent_companies
    person_companies.select{|x| x if !x.active }.collect{|x| x.company}
  end


  def new_person_companies_attributes=(attr)
    attr.each do |a|
      person_companies.build(a) if (a['company_id'] && !a['_destroy'] == 'true')
    end
  end

  def existing_person_companies_attributes=(attr)
    attr.each do |x, y|
      comp = PersonCompany.find(y['id'])
      comp.update_attributes(:active => y['active'], :company_id => y['company_id'])
      if y['_destroy'] == 'true'
        comp.delete
      end
    end
  end


  def self.search(word)
    self.where(:name.matches => "#{word}%")
  end

#  define_index do
#    indexes :name
#  end


  before_save :set_nationality
  after_save :save_companies

  private

  def set_nationality
    self.country = Country.find_by_name('Other') if !self.country
  end

  def save_companies
    person_companies.each do |comp|
      comp.save(false)
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  respond_to :html, :rss
  before_filter :login_required, :except => [:index, :show]

  def index
    @curr_page = 'people'
    @countries = Country.all
    @recent_people = Person.order('created_at DESC').limit(3)
    unless params[:search]
      @persons = Person
    else
      @persons = Country.find(params[:search][:nationality_id]).people
    end
  end
  
  def new
    @curr_page = 'people'
    @person = Person.new
    @person.person_companies.build
  end

  def edit
    @curr_page = 'people'
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      redirect_to @person, :notice => "Person information updated."
    else
      flash[:error] = "Can't update person"
      render :action => 'edit'
    end
  end

  def create
    @person = Person.new(params[:person])
    if @person.save
      redirect_to people_url, :notice => "New person created."
    else
      render :action => "new", :error => "try again"
    end
  end

  def show
    @curr_page = 'people'
    @person = Person.find(params[:id])
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
  def fields_for_person_company(comp, &block)
    prefix = comp.new_record? ? 'new' : 'existing'
    fields_for("person[#{prefix}_person_companies_attributes][]", comp, &block)
  end

  def add_person_company_link(name)
    link_to_function name do |page|
      page.insert_html :bottom, "person_companies", :partial => 'person_company', :object => PersonCompany.new
    end
  end

  def person_links(person)
    links = []
    if person.link1_url && person.link1_url.any?
      links << link_to( (person.link1_name.any? ? person.link1_name : person.link1_url), person.link1_url)
    end

    if person.link2_url && person.link2_url.any?
      links << link_to( (person.link2_name.any? ? person.link2_name : person.link2_url), person.link2_url)
    end
    
    if person.link3_url && person.link3_url.any?
      links << link_to( (person.link3_name.any? ? person.link3_name : person.link3_url), person.link3_url)
    end

    if person.link4_url && person.link4_url.any?
      links << link_to( (person.link4_name.any? ? person.link4_name : person.link4_url), person.link4_url)
    end
    links.join('<br />')
  end
end

app/views/people/_form.html.erb
<%= form_for @person, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.error_messages %>
  </p>
  <p>
    <%= f.label :name, 'Name'%><br />
    <%= f.text_field :person_name %>
  </p>
  <p>
    <%= f.check_box :investor %>
    <%= f.label :investor, 'Angel investor'%>
    <label for="person_investor">Angel investor</label>
  </p>

  <p>
    <%= f.label :picture %><br />
    <i style="font-size:9px;">File size needs to be less than 1MB.</i><br/>
    <input id="person_picture" name="person[picture]" size="30" type="file" />
  </p>

  <p>
    <strong><%= f.label 'Companies'%></strong><br />
  <div id="person_companies">
    <%= render :partial => 'person_company', :collection => @person.person_companies %>
  </div>
  <%= add_person_company_link "New company" %>


  </p>

  <p>
    <%= f.label :overview %> (HTML-tags are not supported)<br />
    <i style="font-size:9px;">Please provide a neutral, third party description of this person.</i><br/>
    <%= f.text_area :overview, :size=>'40x20' %>
  </p>

  <p>
    <%= f.label :academic_degrees %><br />
    <%= f.text_area :academic_degrees, :size=>'40x20' %>
  </p>

  <p>
    <%= f.label :country_id, 'Nationality'%>
    <%= f.select :country_id,  Country.all.collect {|p| [ p.name, p.id ] }, { :include_blank => '' }%>
  </p>

  <p>
    <%= f.label :blog_feed, 'Blog feed (RSS/Atom)' %><br/>
    <%= f.text_field :blog_feed %>
  </p>

  <p>
    <b><%= f.label :link1_url, 'Link 1' %></b><br />
    Name<br/><%= f.text_field :link1_name %><br/>
    Url<br/><%= f.text_field :link1_url %>
  </p>

  <p>
    <b><%= f.label :link2_url, 'Link 2' %></b><br />
    Name<br/><%= f.text_field :link2_name %><br/>
    Url<br/><%= f.text_field :link2_url %>
  </p>

  <p>
    <%= f.label :link3_url, 'Link 3' %><br />
    Name<br/><%= f.text_field :link3_name %><br/>
    Url<br/><%= f.text_field :link3_url %>
  </p>

  <p>
    <%= f.label :link4_url, 'Link 4' %><br />
    Name<br/><%= f.text_field :link4_name %><br/>
    Url<br/><%= f.text_field :link4_url %>
  </p>

  <%= f.submit 'Submit' %>

<% end %>

<script type="text/javascript">
  function remove_fields(link) {
    $(link).prev("input[type=hidden]").val("true");
    $(link).closest(".fields").hide();
  }

  function add_fields(link, association, content) {
    var new_id = new Date().getTime();
    var regexp = new RegExp("new_" + association, "g");
    $(link).parent().before(content.replace(regexp, new_id));
  }
</script>

app/views/people/_person_company.html.erb
<p class="fields">
  <%= fields_for_person_company(person_company) do |com| %>
        <%= com.hidden_field :id %>
        <%= com.check_box :active  %>
        <%= com.select :company_id, Company.all.collect {|c| [ c.name, c.id ] } %>
        <%= com.hidden_field :_destroy %>
        <%= link_to_function "remove", "remove_fields(this)" %>
  <%end%>
</p>

app/views/people/edit.html.erb
<h1>Persons#edit</h1>
<% content_for :left do %>
  <p>
    Please fill in the personal data accordingly to the fields provided.
    When describing the person in question, please use a third person tone and avoid using marketing language.
    We wish to keep the database as neutral as possible and thus as useful for everyone as possible.
  </p>
<%  end %>


<%= render :partial => 'form' %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<% content_for :left do %>
  <a href="/people.rss"><img src="/images/rss.png" style="position:relative;top:2px" border="0" /> RSS for people</a><br/><br/>
  <h3>Contribute</h3>

  <p><%= link_to "Add New Person »", new_person_path, :class=>'app'%></p>

  <h3>Filter people</h3>
  By nationality<br/>
  <p>
    <% for c in @countries do %>
        <%= link_to "#{c.name} (#{c.people.count})", "/people?search[nationality_id]=#{c.id}" , :class => "app" %><br />
    <% end %>
  </p>
<%-  end -%>


<table class="companylist">
  <tbody>
    <% @persons.order('name').group_by{|x| x.name[0...1]}.each do |x,y|  %>
      <tr>
        <td colspan="3">
          <h4><%= x.upcase %></h4>
        </td>
      </tr>
      <%  y.in_groups_of(2, false) do |persons| %>
        <tr>
          <% for pers in persons %>
            <td><%= link_to pers.full_name, pers %></td>
          <% end %>
        </tr>

      <% end %>
    <%  end %>
  </tbody>
</table>


  <% content_for :right do %>
      <h3>Recently added</h3>
      <ul class="sidenews">
        <% for p in @recent_people %>
          <li><%= link_to p.name, p %></li>
        <% end %>
      </ul>
    <%  end %>

app/views/people/new.html.erb
<h1>Add New Person</h1>

<% content_for :left do %>
  Please fill in the personal data accordingly to the fields provided.
  When describing the person in question, please use a third person tone and avoid using marketing language.
  We wish to keep the database as neutral as possible and thus as useful for everyone as possible.
<%  end %>

<%= render :partial => 'form' %>

app/views/people/show.html.erb
<% content_for :left do %>
  <p>
    <%= image_tag @person.picture.url(:big) %>
  </p>

  <h3>Academic Degrees</h3>
  <%= simple_format(h(@person.academic_degrees)) %>

  <h3>Nationality</h3>
  <p><%= @person.country.name %></p>


<%  end %>

<h1><%=h @person.name %></h1>
<p>
  <%= link_to "Edit", edit_person_path(@person) %> |
  <%= link_to "Report Abuse", abuses_path(:id => @person.id, :type => @person.class.to_s), :method=>:post %>
</p>

<% if @person.overview %>
  <p>
    <%=  simple_format(h(@person.overview))%>
  </p>
<% end %>

<h2>Current companies</h2>
<% current_comp =  @person.current_companies %>
<% if current_comp.any? %>
  <% for c in current_comp %>
    <%= link_to c.name, c %><br />
  <% end %>
<%else%>
  No companies
<%end%>


<h2>Previous companies</h2>
<% incurrent_comp =  @person.incurrent_companies %>
<% if incurrent_comp.any? %>
  <% for c in @person.incurrent_companies %>
    <%= link_to c.name, c %><br />
  <% end %>
<%  else %>
  No companies
<% end %>


  <h2>Links</h2>

<%=raw person_links(@person) %>