config/routes.rb
ArcticIndexClone::Application.routes.draw do

  resources :feedbacks

  match "jobs/job_select" =>'jobs#job_select', :method => :get, :as => :job_select
  resources :jobs, :except => [:destroy]
  
  resources :admin, :only => [:index, :destroy]
  resources :events

  match "search" =>'search#index', :method => :get

  resources :companies, :except => [:destroy]
  resources :people do
    resources :companies, :controller => :people_companies
  end

  resources :users#, :only => [:new, :create, :show, :edit]
  match 'profile'   => 'users#profile',  :as => :profile
  match 'profile/edit'   => 'users#edit',  :as => :profile
  
  resource  :session, :only => [:new, :create, :destroy]
  resources :investors, :only => :index
  resources :abuses, :only => [:create, :desatroy]
  resources :authorizations, :only => :destroy

  match 'signup'   => 'users#new',        :as => :signup
  match 'register' => 'users#create',     :as => :register
  match 'login'    => 'sessions#new',     :as => :login
  match 'logout'   => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match '/auth/:provider/callback', :to => 'authorizations#create'

  root :to => "home#index"
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_filter :login_required, :except => [:index, :show]

  def index
    @curr_page = 'jobs'
    @all_jobs = Job.all
  end

  def show
    @curr_page = 'jobs'
    @job = Job.find(params[:id])
  end

  def edit
    @curr_page = 'jobs'
    @job = Job.find(params[:id])
  end

  def update
    attributes = params[:job_person] ? params[:job_person] : params[:job_company]
    @job = Job.find(params[:id])
    if current_user.jobs.include?(@job) or current_user.admin?
      if(@job.update_attributes(attributes))
        flash[:notice] = 'Job updated'
        redirect_to job_path(@job)
      else
        flash[:error] = 'Can\'t update job'
        render 'edit'
      end
    else
      flash[:error] = "You haven't rights to do that"
      redirect_to jobs_path
    end
  end

  def new
    @curr_page = 'jobs'
    if (params[:job_type] == 'person')
      @job= JobPerson.new
    elsif(params[:job_type] == 'company')
      @job= JobCompany.new
    else
      flash[:error] = 'Parameters error, try again'
      redirect_to jobs_path
    end
  end

  def job_select
    @curr_page = 'jobs'
  end

  def create
    attributes = params[:job_person] ? params[:job_person] : params[:job_company]
    @job = params[:job_person] ? JobPerson.new(attributes) : JobCompany.new(attributes)
    if(@job.save)
      current_user.jobs << @job
      flash[:notice] = 'Job saved'
      redirect_to jobs_path
    else
      flash[:error] = 'Can\'t save job'
      render 'new'
    end
  end

end

app/helpers/jobs_helper.rb
module JobsHelper

  def it_my_job_posting?(job)
    current_user && current_user.jobs.include?(job)
  end
end

app/views/jobs/_company_form.html.erb
<h1>Add New Job Posting</h1>

<% path = @new ? jobs_path : job_path(@job) %>
<%= form_for @job, :url => path do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :company_id, 'Company'%>
    <%= f.select :company_id,  Company.all.collect {|p| [ p.name, p.id ] }%>
  </p>
  <p>
    Can't find your company? <%= link_to "Add it to the index", new_company_path %>.
  </p>

  <p>
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </p>

  <p>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </p>

  <p>
    <input type="radio" value="true" name="job_company[full_time]" id="full_time_true" checked="checked" /> Full time<br />
    <input type="radio" value="false" name="job_company[full_time]" id="full_time_false" /> Part time
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :compensation %><br />
    <%= f.text_field :compensation %>
  </p>

  <p>
    <%= f.label :applying_instructions %><br />
    <%= f.text_field :applying_instructions %>
  </p>

  <p>
    <%= f.label :last_application_date %><br />
    <%= f.date_select :last_application_date %>
  </p>

  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/jobs/_person_form.html.erb
<h1>What are you looking for?</h1>

<% path = @new ? jobs_path : job_path(@job) %>
<%= form_for @job, :url => path do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :person_id, 'Person'%>
    <%= f.select :person_id,  Person.all.collect {|p| [ p.name, p.id ] }%>
  </p>
  <p>
    Can't find your profile? <%= link_to "Add it to the index", new_person_path %>.
  </p>

  <p>
    <input type="radio" value="true" name="job_person[cofounders]" id="founder_founder_true" checked="checked" /> co-founders?<br />
    <input type="radio" value="false" name="job_person[cofounders]" id="founder_founder_false" /> a great startup to join
  </p>
 
  <p>
    <%= f.label :skill_set, 'Your skillset (What you bring to the table)' %><br />
    <%= f.text_area :skill_set %>
  </p>

  <p>
    <%= f.label :ideal_skill_set, 'Ideal Skillset In Your Co-founder / Ideal Startup To Join' %><br />
    <%= f.text_area :ideal_skill_set %>
  </p>

  <p>
    <%= f.label :area_of_interests %><br />
    <%= f.text_area :area_of_interests %>
  </p>

  <p>
    <%= f.label :other_comments %><br />
    <%= f.text_area :other_comments %>
  </p>

  <p>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :last_application_date %><br />
    <%= f.date_select :last_application_date %>
  </p>


  
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/jobs/_show_company.html.erb
<% content_for :left do %>

  <%= image_tag @job.company.picture.url(:big) %>

  <h3>General information</h3>

  <table>
    <tbody><tr>
        <td><strong>Website</strong></td>
        <td> <%= link_to @job.company.name, @job.company.website %></td>
      </tr>
      <tr>
        <td><strong>Blog</strong></td>
        <td><%=link_to @job.company.blog, @job.company.blog %></td>
      </tr>
      <tr>
        <td><strong>Category</strong></td>
        <td><%= link_to @job.company.category.name, "/companies?search[category_id]=#{@job.company.category.id}" %></td>
      </tr>
      <tr>
        <td><strong>Phone</strong></td>
        <td><%=h @job.company.phone %></td>
      </tr>
      <tr>
        <td><strong>Employees</strong></td>
        <td><%=h @job.company.employers %></td>
      </tr>
      <tr>
        <td><strong>Country</strong></td>
        <td><%=h @job.company.country.name %></td>
      </tr>
      <tr>
        <td><strong>City</strong></td>
        <td><%=h @job.company.city %></td>
      </tr>

      <tr>
        <td><strong>Founded</strong></td>
        <td><%=@job.company.founded_at.strftime('%b, %Y') %> </td>
      </tr>

    </tbody>
  </table>
<%  end %>


<h1><%= link_to "Jobs » ", jobs_path, :class => 'app' %><%=h @job.position %></h1>

<p>
  <strong>Company:</strong>
  <%= link_to @job.company.name, @job.company %><br />
  <strong>Position:</strong>
  <%=h @job.position %><br />
  <strong>Location:</strong>
  <%=h @job.location %><br />
  <strong>Job Type:</strong>
  <%= @job.full_time ? 'Full time' : 'Part time' %><br />
</p>

<h4>Description:</h4>
<%= simple_format(h(@job.description)) %>
<p>
  <strong>Compensation:</strong>
  <%=h @job.compensation %><br />
  <strong>Created:</strong>
  <%= @job.created_at.to_s(:simple_date) %>
</p>

<h4>To apply</h4>
<p>
  <%=h @job.applying_instructions %>
</p>

<p>
  <strong>Last application date:</strong>
  <%= @job.last_application_date.to_s(:simple_date) %><br />
</p>

<% if it_my_job_posting?(@job) or current_user && current_user.admin? %>
  <p>
    <%= link_to 'Edit', edit_job_path(@job) %> | <%= link_to 'Back to jobs', jobs_path %>
  </p>
<% else %>
  <p>
    <%= link_to 'Back to jobs', jobs_path %>
  </p>
<% end %>

app/views/jobs/_show_person.html.erb
<h1>
  <%= link_to "Jobs » ", jobs_path, :class => 'app' %>
  <%= @job.cofounders ? ' Looking for co-founder' : 'Looking for great startup to join' %>
</h1>

<% content_for :left do %>
  <%= image_tag @job.person.picture.url(:big) %>
<%  end %>

<p>
  <strong>Person:</strong>
  <%= link_to @job.person.name, @job.person %><br />
  <strong>Location:</strong>
  <%=h @job.location %><br />
  <strong>Type:</strong>
  <%= @job.cofounders ? ' Looking for co-founders' : 'Looking for great startup to join' %><br />
</p>

<h4>Person's skillset:</h4>
  <%= simple_format(h(@job.skill_set)) %>

<h4>Ideal skillset looking for:</h4>
  <%= simple_format(h(@job.ideal_skill_set)) %>

<h4>Primary areas of interest:</h4>
  <%= simple_format(h(@job.area_of_interests)) %>

<h4>Other comments:</h4>
  <%= simple_format(h(@job.other_comments)) %>

<p>
  <strong>Created:</strong>
  <%= @job.created_at.to_s(:simple_date) %>
</p>

<p>
  <strong>Last application date:</strong>
  <%= @job.last_application_date.to_s(:simple_date) %><br/>
</p>

<p>
  <%= link_to "Edit", :action => "edit" %> |
  <a href="/jobs">View all jobs</a>
</p>

app/views/jobs/edit.html.erb
<% content_for :left do %>
  <p>Recruiting? Great! Add your job description and needs regarding the
    position to the form on the right.</p>

  <p>Start off with choosing your company from the list, if it's not there yet
    - no worries, <%= link_to "add it here", new_company_path %> .</p>

  <p>Once it's added, fill in the position, location, whether it's a part time
    job or a full-time job, what's required from the perso applying
    (description), compensation, applying instructions and when you want your
    job application to expire. Once a job post has expired, it will not be
    shown to the public anymore.</p>

  <p>Once you have filled in all the information, hit the submit button. If you
    had a typo in the form, just hit the edit button on the next page and you
    can go back and change whatever you need to.</p>
<%  end %>

<%= @job.class.to_s == 'JobPerson' ? render('person_form') : render('company_form') %>

app/views/jobs/index.html.erb
<h1>Open positions</h1>

<% content_for :left do %>

  <a href="/jobs.rss"><img border="0" style="position: relative; top: 2px;" src="/images/rss.png" /> RSS for jobs</a>
  <br /><br />
  <%= link_to "Add new job or job/co-founder application »", job_select_path, :class => 'app' %><br />
  <a href="#open_positions" class="app">Open Positions</a><br />
  <a href="#cofounders_wanted" class="app">Co-founders Wanted / Want to Join Startup</a><br />
<%  end %>

<table class="joblist">
  <thead>
    <tr>
      <th>Company</th>
      <th>Position</th>
      <th>Last date</th>
    </tr>
  </thead>
  <tbody>
    <% @all_jobs.select{|x| x if x.is_a?(JobCompany)}.group_by{|x| x.created_at.beginning_of_day}.each do |day, jobs| %>
      <tr>
        <td colspan="3"><h4><%= jobs.first.created_at.to_s(:simple_date) %></h4></td>
      </tr>
      <% for j in jobs %>
        <tr class="info">
          <td>
            <b>
              <%= link_to j.company.name, j.company %>
            </b>
          </td>
          <td>
            <%=link_to j.position, job_path(j) %>
          </td>
          <td>
            <%=  j.last_application_date.to_s(:client_reports)  %>
          </td>
        </tr>
      <%  end %>
    <%  end %>
  </tbody>
</table>
  <br />

  <h1>Looking for founders / startups</h1>

<table class="joblist">
  <thead>
    <tr>
      <th>Person</th>
      <th>Looking for</th>
      <th>Last date</th>
    </tr>
  </thead>
  <tbody>
    <% @all_jobs.select{|x| x if x.is_a?(JobPerson)}.group_by{|x| x.created_at.beginning_of_day}.each do |day, jobs| %>
      <tr>
        <td colspan="3"><h4><%= jobs.first.created_at.to_s(:simple_date) %></h4></td>
      </tr>
      <% for j in jobs %>
        <tr class="info">
          <td>
            <b>
              <%= link_to j.person.name, j.person %>
            </b>
          </td>
          <td>
            <%= link_to j.cofounders ? 'co-founder' : 'a great sturtup to join', job_path(j) %>
          </td>
          <td>
            <%=  j.last_application_date.to_s(:client_reports)  %>
          </td>
        </tr>
      <%  end %>
    <%  end %>
  </tbody>
</table>

<script>
  $("tr.info:odd").attr('class', 'odd');
  $("tr.info:even").attr('class', 'even');
</script>

app/views/jobs/job_select.html.erb
<% content_for :left do %>
  <p>Recruiting? Great! Add your job description and needs regarding the
    position to the form on the right.</p>

  <p>Start off with choosing your company from the list, if it's not there yet
    - no worries, <%= link_to "add it here", new_company_path %> .</p>

  <p>Once it's added, fill in the position, location, whether it's a part time
    job or a full-time job, what's required from the perso applying
    (description), compensation, applying instructions and when you want your
    job application to expire. Once a job post has expired, it will not be
    shown to the public anymore.</p>

  <p>Once you have filled in all the information, hit the submit button. If you
    had a typo in the form, just hit the edit button on the next page and you
    can go back and change whatever you need to.</p>
<%  end %>


  <div class="select_job_links">
     <%= link_to "I'm a company looking for great people to hire", :action => "new", :job_type => 'company' %><br />
     <%= link_to "I'm an individual looking for co-founder(s) / a great startup to join ", :action => "new", :job_type => 'person' %>
</div>
  <%= link_to "Back", :action => "index" %>

app/views/jobs/new.html.erb
<% content_for :left do %>
  <p>Recruiting? Great! Add your job description and needs regarding the
    position to the form on the right.</p>

  <p>Start off with choosing your company from the list, if it's not there yet
    - no worries, <%= link_to "add it here", new_company_path %> .</p>

  <p>Once it's added, fill in the position, location, whether it's a part time
    job or a full-time job, what's required from the perso applying
    (description), compensation, applying instructions and when you want your
    job application to expire. Once a job post has expired, it will not be
    shown to the public anymore.</p>

  <p>Once you have filled in all the information, hit the submit button. If you
    had a typo in the form, just hit the edit button on the next page and you
    can go back and change whatever you need to.</p>
<%  end %>


<% @new = true %>
<%= @job.class.to_s == 'JobPerson' ? render('person_form') : render('company_form') %>
  
<%= link_to 'Back to jobs', jobs_path %>

app/views/jobs/show.html.erb
<%= @job.class.to_s == 'JobPerson' ? render('show_person') : render('show_company') %>