config/routes.rb
ArcticIndexClone::Application.routes.draw do

  resources :feedbacks

  match "jobs/job_select" =>'jobs#job_select', :method => :get, :as => :job_select
  resources :jobs, :except => [:destroy]
  
  resources :admin, :only => [:index, :destroy]
  resources :events

  match "search" =>'search#index', :method => :get

  resources :companies, :except => [:destroy]
  resources :people do
    resources :companies, :controller => :people_companies
  end

  resources :users#, :only => [:new, :create, :show, :edit]
  match 'profile'   => 'users#profile',  :as => :profile
  match 'profile/edit'   => 'users#edit',  :as => :profile
  
  resource  :session, :only => [:new, :create, :destroy]
  resources :investors, :only => :index
  resources :abuses, :only => [:create, :desatroy]
  resources :authorizations, :only => :destroy

  match 'signup'   => 'users#new',        :as => :signup
  match 'register' => 'users#create',     :as => :register
  match 'login'    => 'sessions#new',     :as => :login
  match 'logout'   => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match '/auth/:provider/callback', :to => 'authorizations#create'

  root :to => "home#index"
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :people, :through => :person_companies
  has_many :person_companies
  has_many :job_companies
  belongs_to :country
  belongs_to :category
  
  has_attached_file :picture, :styles => { :big => "225x215>", :thumb => "70x35>" },
     :url=>'/images/companies/:id/:style/:filename',
     :default_url=>'/images/no_image_:style.png'
  validates_attachment_size :picture, :less_than => 1.megabyte
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/gif']

  validates :name, :presence => true
  validates :employers, :numericality => true

  def current_people
    person_companies.select{|x| x if x.active}.collect{|x| x.person}.compact
  end

  def self.search(word)
    self.where(:name.matches => "#{word}%")
  end
#  define_index do
#    indexes :name
#  end


  before_save :set_category

  private

  def set_category
    self.category = Category.find_by_name('Other') if !self.category
  end
end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base
  before_filter :login_required, :except => [:index, :show]
  
  def index
    @curr_page = 'companies'
    @countries = Country.all
    @categories = Category.all
    @recent_companies = Company.order('created_at DESC').limit(3)
    unless params[:search]
      @companies = Company
    else
      @companies = Country.find(params[:search][:nationality_id]).companies if params[:search][:nationality_id]
      @companies = Category.find(params[:search][:category_id]).companies if params[:search][:category_id]
    end
  end

  def new
    @curr_page = 'companies'
    @company = Company.new
    @company.website = 'http://'
  end

  def edit
    @curr_page = 'companies'
    @company = Company.find(params[:id])
  end

  def show
    @curr_page = 'companies'
    @company = Company.find(params[:id])
  end


end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.error_messages %>
  </p>

  <br />
    <%= f.label :name, 'Name'%><br />
    <%= f.text_field :name %>


  <br />
    <%= f.label :category_id, 'Category'%><br />
    <%= f.select :category_id,  Category.all.reject(&:regectable?).collect {|p| [ p.name, p.id ] }, { :include_blank => '' }%>
 
  <br />
    <%= f.label :picture %><br />
    <i style="font-size:9px;">File size needs to be less than 1MB.</i><br/>
    <input id="person_picture" name="company[picture]" size="30" type="file" />

  <br />
    <%= f.label :description %> (HTML-tags are not supported)<br />
    <i style="font-size:9px;">Please provide a neutral, third party description of this person.</i><br/>
    <%= f.text_area :description, :size=>'40x20' %>

  <br />
    <%= f.label :website%><br />
    <%= f.text_field :website %>

  <br />
    <%= f.label :blog %><br/>
    <%= f.text_field :blog %>

  <br />
    <%= f.label :blog_feed, 'Blog feed (RSS/Atom)' %><br/>
    <%= f.text_field :blog_feed %>

  <br />
    <%= f.label :phone %><br/>
    <%= f.text_field :phone %>

<br />
    <%= f.label :employers %><br/>
    <%= f.text_field :employers %>

 <br />
    <%= f.label :city %><br/>
    <%= f.text_field :city %>

<br />
    <%= f.label :country_id, 'Country'%><br />
    <%= f.select :country_id,  Country.all.collect {|p| [ p.name, p.id ] }, { :include_blank => '' }%>


  <br />
    <%= f.label :founded_at, 'Founded'%>
    <%= f.date_select :founded_at, :start_year => 1993, :end_year => Time.now.year, :discard_day => true %>
  <br />
  <%= f.label :not_known%>
  <%= f.check_box :not_known %>
  <br />
  <%= f.submit 'Submit' %>
  <br />
  <%= link_to "Back", companies_path %>

<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<% content_for :left do %>
  Please fill in the company data accordingly to the fields provided.
  When describing the company, please use a third person tone and avoid using marketing language.
  We wish to keep the database as neutral as possible and thus as useful for everyone as possible.
<%  end %>


<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<% content_for :left do %>
  <a href="/companies.rss"><img src="/images/rss.png" style="position:relative;top:2px" border="0" /> RSS for companies</a><br/><br/>
  <h3>Contribute</h3>

  <p><%= link_to "Add New Company »", new_company_path, :class=>'app'%></p>

  <h3>Filter companies</h3>
  By nationality<br/>
  <p>
    <% for c in @countries do %>
        <%= link_to "#{c.name} (#{c.companies.count})", "/companies?search[nationality_id]=#{c.id}" , :class => "app" %><br />
      <% end %>
    </p>

    By type<br/>
    <p>
      <% for c in @categories do %>
          <%= link_to "#{c.name} (#{c.companies.count})", "/companies?search[category_id]=#{c.id}" , :class => "app" %><br />
        <% end %>
      </p>
    <%  end %>

    <table class="companylist">
      <tbody>
        <% @companies.order('name').group_by{|x| x.name[0...1]}.each do |x,y|  %>
          <tr>
            <td colspan="3">
              <h4><%= x.upcase %></h4>
            </td>
          </tr>
          <%  y.in_groups_of(2, false) do |companies| %>
            <tr>
              <% for comp in companies %>
                <td><%= link_to comp.name, comp %></td>
              <% end %>
            </tr>
          <% end %>
        <%  end %>
      </tbody>
    </table>



    <% content_for :right do %>
      <h3>Recently added</h3>
      <ul class="sidenews">
        <% for c in @recent_companies %>
          <li><%= link_to c.name, c %></li>
        <% end %>
      </ul>
    <%  end %>

app/views/companies/new.html.erb
<h1>Add New Company</h1>

<% content_for :left do %>
  Please fill in the company data accordingly to the fields provided.
  When describing the company, please use a third person tone and avoid using marketing language.
  We wish to keep the database as neutral as possible and thus as useful for everyone as possible.
<%  end %>


<%= render :partial => 'form' %>

app/views/companies/show.html.erb
<% content_for :left do %>

  <%= image_tag @company.picture.url(:big) %>

  <h3>General information</h3>

  <table>
    <tbody><tr>
        <td><strong>Website</strong></td>
        <td> <%= link_to @company.name, @company.website %></td>
      </tr>
      <tr>
        <td><strong>Blog</strong></td>
        <td><%=link_to @company.blog, @company.blog %></td>
      </tr>
      <tr>
        <td><strong>Category</strong></td>
        <td><%= link_to @company.category.name, "/companies?search[category_id]=#{@company.category.id}"  %></td>
      </tr>
      <tr>
        <td><strong>Phone</strong></td>
        <td><%=h @company.phone %></td>
      </tr>
      <tr>
        <td><strong>Employees</strong></td>
        <td><%=h @company.employers %></td>
      </tr>
      <tr>
        <td><strong>Country</strong></td>
        <td><%=h @company.country.name %></td>
      </tr>
      <tr>
        <td><strong>City</strong></td>
        <td><%=h @company.city %></td>
      </tr>

      <tr>
        <td><strong>Founded</strong></td>
        <td><%=@company.founded_at.strftime('%b, %Y') %> </td>
      </tr>

    </tbody>
  </table>
<%  end %>

<h1><%=h @company.name %></h1>
<p>
  <%= link_to "Edit", edit_company_path(@company) %> |
  <%= link_to "Report Abuse", abuses_path(:id => @company.id, :type => @company.class.to_s), :method=>:post %>
</p>

<p>
  <%= simple_format(h(@company.description))%>
</p>


<% current_peopl = @company.current_people %>
<% if current_peopl.any? %>
  <h2>Currently associated people</h2>
  <%for p in current_peopl %>
    <%= link_to p.name, p %><br />
  <%  end %>
<% end %>