config/routes.rb
ArcticIndexClone::Application.routes.draw do

  resources :feedbacks

  match "jobs/job_select" =>'jobs#job_select', :method => :get, :as => :job_select
  resources :jobs, :except => [:destroy]
  
  resources :admin, :only => [:index, :destroy]
  resources :events

  match "search" =>'search#index', :method => :get

  resources :companies, :except => [:destroy]
  resources :people do
    resources :companies, :controller => :people_companies
  end

  resources :users#, :only => [:new, :create, :show, :edit]
  match 'profile'   => 'users#profile',  :as => :profile
  match 'profile/edit'   => 'users#edit',  :as => :profile
  
  resource  :session, :only => [:new, :create, :destroy]
  resources :investors, :only => :index
  resources :abuses, :only => [:create, :desatroy]
  resources :authorizations, :only => :destroy

  match 'signup'   => 'users#new',        :as => :signup
  match 'register' => 'users#create',     :as => :register
  match 'login'    => 'sessions#new',     :as => :login
  match 'logout'   => 'sessions#destroy', :as => :logout
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  match '/auth/:provider/callback', :to => 'authorizations#create'

  root :to => "home#index"
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < InheritedResources::Base

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.email %></td>
    <td><%= feedback.message %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @feedback.email %>
</p>

<p>
  <b>Message:</b>
  <%= @feedback.message %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>